name: frontend deployment
run-name: Frontend deployment update triggered by ${{ github.actor }} :- ${{ github.run_number }}.

on:
  push:
    branches:
      - deployment
    paths:
      - .github/workflows/frontendDeploy.yml
      - frontend/**
      
env:
  GITHUB_USER: paritosh-pranjal
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

jobs:
  frontend:
    name: frontend image build and deploy
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-node_modules-${{ hashFiles('frontend/package.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the docker image to ghcr
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{env.GITHUB_USER }}/bootcamp26-frontend:latest

  deploy:
    name: Frontend EC2 Deploy
    needs: frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          sudo chmod 600 key.pem

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_FRONTEND_IP }} '
            docker login --username "${{ github.repository_owner }}" --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io &&
            docker pull ghcr.io/${{env.GITHUB_USER }}/bootcamp26-frontend:latest &&
            docker-compose down
            docker-compose -f /home/ubuntu/docker-compose.yml up -d
          '